SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `itens_pedidos`;
DROP TABLE IF EXISTS `produtos`;
DROP TABLE IF EXISTS `categorias`;
DROP TABLE IF EXISTS `pedidos`;
DROP TABLE IF EXISTS `clientes`;
DROP TABLE IF EXISTS `vendedores`;

SET FOREIGN_KEY_CHECKS = 1;
